Ui Tweaks
HaikuTeam/animator pull request #170
Opened 2018-01-03 00:54 UTC by taylorpoe

**Has been reviewed/approved:**
* Updates various small icon, coloring, & layout details
* Updates css transition group package from the old deprecated package to the suggested one [instructions on the package we were using](https://www.npmjs.com/package/react-addons-css-transition-group)
* Disallow project creation if name is blank

**Still needs review:**
* Only show the actions bolt icon next to collapsed element rows names if it _has_ actions attached. 
* Fixes actions icons to change to blue immedately when elements are given actions
* put ticker line above collapsed rows
* Fixes click area of frame events to not respond to gauge numbers being clicked
* Brings ticker bulb up on top of numbers to reduce overall gauge height — had to put the numbers back in the bulb because the bulb now covers the numbers.

2018-01-03 01:13 UTC, stristr commented
Deps management LGTM, have not reviewed code.

2018-01-03 14:28 UTC, roperzh requested changes
LGTM, the only necessary change to make is a lint pass (`yarn lint-all`), as there are unused variables and other lint issues

2018-01-03 14:28 UTC, roperzh commented on packages/haiku-creator/public/stylesheets/global.css
> +  opacity: .01;
_extreme nit_: `0.01` reads much more clearly for me, but whatever we choose should be consistent across the file.

2018-01-03 14:28 UTC, roperzh commented on packages/haiku-creator/src/react/components/ProjectBrowser.js
> +    if (!raw) return false
_nit_: would prefer a more explicit name like `rawProjectName` or similar

2018-01-03 15:08 UTC, tsortwehttam commented on packages/haiku-creator/src/react/components/ProjectBrowser.js
> +    if (!raw) return false
What if the string is `"    "` or `"\n   "`?

2018-01-03 15:10 UTC, tsortwehttam commented on packages/haiku-creator/src/react/components/ProjectBrowser.js
> +    if (!raw) return false
That bad variable name is my doing and I agree it should be changed.

2018-01-03 16:58 UTC, taylorpoe commented on packages/haiku-creator/src/react/components/ProjectBrowser.js
> +    if (!raw) return false
Spaces and slashes are both ignored as the user is typing; so they won't ever end up here.

2018-01-03 16:58 UTC, taylorpoe commented on packages/haiku-creator/src/react/components/ProjectBrowser.js
> +    if (!raw) return false
updated

2018-01-03 16:58 UTC, taylorpoe commented on packages/haiku-creator/public/stylesheets/global.css
> +  opacity: .01;
updated

2018-01-03 17:17 UTC, roperzh approved these changes

2018-01-03 17:17 UTC, roperzh commented
:shipit:

2018-01-04 00:10 UTC, taylorpoe commented
Oops, I incorrectly thought this was already merged when I saw that the PR was approved. I have a few new commits here that will need to be reviewed/approved. I will outline the full scope in the PR message.

2018-01-04 00:14 UTC, tsortwehttam commented
LGTM.

2018-01-04 01:30 UTC, roperzh commented
LGTM.

2018-01-04 23:22 UTC, merged