Feat email verification
HaikuTeam/animator pull request #255
Opened 2018-01-26 21:07 UTC by roperzh

OK to merge.

Short review.

Asana task link: https://app.asana.com/0/480796620059175/521587463583421

Changes in this PR:

- [x] Show errors directly from inkstone instead of hardcoding 'Username or Password Incorrect'
- [x] Add endpoints to `sdk-instone` featuring email confirmation and resend email confirmation
- [x] Add a different color to the 'user not verified' error 

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [ ] Did the [E2E checklist](https://haiku.quip.com/dGqeAEVSWdmg)
- [x] Expanded the [QA checklist](https://haiku.quip.com/rqwsAPsCGxqT)
- [x] Ran the automated tests and linted the code
- [ ] Wrote an automated test covering new functionality

2018-01-26 21:54 UTC, stristr requested changes

2018-01-26 21:54 UTC, stristr commented on packages/haiku-plumbing/src/Plumbing.js
> +    inkstone.setConfig({ baseUrl: 'https://localhost:8080/' })
Gotta remove this before okay to merge.

`.env` is the new way :smile:!

2018-01-26 22:24 UTC, roperzh commented on packages/haiku-plumbing/src/Plumbing.js
> +    inkstone.setConfig({ baseUrl: 'https://localhost:8080/' })
damn! sorry about that

2018-01-27 17:28 UTC, stristr approved these changes
LGTM.

2018-01-27 17:30 UTC, stristr commented
(Note: to fix lint issue, you just need to `// eslint-disable-next-line standard/no-callback-literal`.)

2018-01-29 21:33 UTC, merged