V0 proxy support
HaikuTeam/animator pull request #302
Opened 2018-02-15 19:03 UTC by roperzh

OK to merge.

Medium review.

Summary of work (include Asana links if any):

- [x] Detect if the user is using proxies, and if so display a message instead of crashing the app: https://app.asana.com/0/539750334128224/548822693280685
- [x] Use `loopback.haiku.ai` as our new host for websocket communications

Regressions to look for:

- Should we expect any kind of regression due to our host change?

Notes for reviewers:

If you want to emulate the crash / test this, you will need to configure your network to use a proxy, you can either fetch a free proxy from the internet or set up your local proxy. I have been using [squidman](http://squidman.net/squidman/) for the latter with great success.

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [x] Ran `$ yarn lint-all` and fixed all formatting issues
- [x] Ran `$ yarn test-all` and all tests passed
- [x] Did the [E2E checklist](https://haiku.quip.com/dGqeAEVSWdmg)
- [x] Expanded the [QA checklist](https://haiku.quip.com/rqwsAPsCGxqT)
- [ ] Wrote an automated test covering new functionality

2018-02-15 23:23 UTC, stristr requested changes
Overall LGTM and nice skillz to get this all to work together!

I am requesting changes because as far as I can tell the current implementation breaks local dev if you don't have an Internet connection to resolve DNS. If I'm incorrect about this, please let me know!

We could hack this with `/etc/hosts` and call it a day, but I would prefer not to depend on a hosts hack for offline dev to be possible.

2018-02-15 23:23 UTC, stristr commented on packages/haiku-common/src/proxies/index.ts
> +  Proxyed = 'PROXY',
Nit (since it's the name of a enum value): `Proxied`

2018-02-15 23:23 UTC, stristr commented on packages/haiku-creator/src/electron.js
> +  haiku.plumbing.url = `http://${global.process.env.HAIKU_PLUMBING_HOST || 'loopback.haiku.ai'}:${global.process.env.HAIKU_PLUMBING_PORT}/?token=${process.env.HAIKU_WS_SECURITY_TOKEN}`
I would actually prefer to keep this default and instead set `HAIKU_PLUMBING_HOST` in the `_config.js.handlebars` in mono root so that we use loopback in releases.

Alternatively, set `HAIKU_PLUMBING_HOST` to `0.0.0.0` in `start.js`.

Doing neither of these things means you can't do local dev on mono without DNS, which requires interwebs.

2018-02-15 23:23 UTC, stristr commented on packages/haiku-plumbing/src/Plumbing.js
> +    host: process.env.HAIKU_CONTROL_HOST || 'loopback.haiku.ai'
(See notes above about not binding local dev to DNS here and below.)

2018-02-15 23:23 UTC, stristr commented on scripts/start.js
> +    global.process.env.HAIKU_PLUMBING_URL = 'http://loopback.haiku.ai:1024'
Per comments above about how local dev shouldn't depend on DNS, let's nix this completely.

2018-02-16 10:58 UTC, roperzh commented on packages/haiku-common/src/proxies/index.ts
> +  Proxyed = 'PROXY',
Damn, sorry about this one. Fixed.

2018-02-16 10:59 UTC, roperzh commented on packages/haiku-creator/src/electron.js
> +  haiku.plumbing.url = `http://${global.process.env.HAIKU_PLUMBING_HOST || 'loopback.haiku.ai'}:${global.process.env.HAIKU_PLUMBING_PORT}/?token=${process.env.HAIKU_WS_SECURITY_TOKEN}`
> I would actually prefer to keep this default and instead set HAIKU_PLUMBING_HOST in the _config.js.handlebars in mono root so that we use loopback in releases.

👍 Fixed, thanks so much for noticing this.

2018-02-16 11:01 UTC, roperzh commented
Thanks so much for the review, all comments are fixed, so this is ready for another review.

Once we merge, I'd like to trigger a build to test, specially considering that `loopback.haiku.ai` is now only set for production.

_edit_: heads up, I rebased against master and thus force pushed this branch.

2018-02-16 16:43 UTC, stristr reviewed
Sorry, caught 2-3 more minor things. Else LGTM!

2018-02-16 16:43 UTC, stristr commented on packages/haiku-plumbing/src/Plumbing.js
> +    host: process.env.HAIKU_CONTROL_HOST || '0.0.0.0'
It looks like this got renamed to `HAIKU_PLUMBING_HOST` in `_config.js.handlebars`, but not here…I don't see it anywhere else so we should probably just change it to var used elsewhere.

2018-02-16 16:43 UTC, stristr commented on packages/haiku-sdk-creator/src/envoy/index.ts
> +  host: '0.0.0.0',
Here and below (`DEFAULT_HOST` in `findOpenPort.ts`): I was reading through and it looks like this doesn't actually get passed by Plumbing in all the right places.

Easy fix should be to change this to `global.process.env.HAIKU_PLUMBING_HOST || '0.0.0.0'` like other things.

2018-02-16 17:13 UTC, roperzh commented on packages/haiku-plumbing/src/Plumbing.js
> +    host: process.env.HAIKU_CONTROL_HOST || '0.0.0.0'
Sorry about this, fixed `HAIKU_CONTROL_HOST` and since we are here I also changed `HAIKU_CONTROL_PORT` for the same reasons.

2018-02-16 17:13 UTC, roperzh commented on packages/haiku-sdk-creator/src/envoy/index.ts
> +  host: '0.0.0.0',
Fixed.

2018-02-16 17:14 UTC, roperzh commented
New batch of requested changes in 4347c2d5f072835c7830d1bf3948db771e627eba, thanks so much for the feedback.

2018-02-16 18:08 UTC, stristr approved these changes
LGTM, let's fire it up!

2018-02-16 18:10 UTC, merged