Add Haiku bytecode definition
HaikuTeam/animator pull request #464
Opened 2018-05-09 07:11 UTC by jonaias

OK to merge.

Short review.

Summary of changes:

Regressions to look for:

Notes for reviewers:

- Need to check the best place to concentrate Haiku types. Note that `haiku-common/src/types/enums.ts` contains types for curve, a type used by Haiku bytecode. My proposal is either to move all Haiku related types to `@haiku/core/api/` or `haiku-common/src/types/`. Curve definition is temporally duplicated until we decide.

- I'll build test cases from demo projects (ideally using them in place). To test locally I used this script
``` bash
mkdir t
cp packages/@haiku/core/api/HaikuBytecode.ts t
cat t/HaikuBytecode.ts >> t/t.ts
echo "function func(tim: HaikuBytecode): boolean {  return false;}" >> t/t.ts

for OUTPUT in $(ls packages/@haiku/core/demo/projects/*/code/main/code.js )
do
    a=`echo $OUTPUT | cut -d/ -f 6`
    cp $OUTPUT t/$a.js
    
    ecapaded=`echo $a | sed -r "s/-/_/g"`
    echo "import * as $ecapaded from './$a'" >> t/t.ts
    echo "func($ecapaded)">> t/t.ts
done 
```
- We might have some problem with nested index signatures on Haiku timeline typedef (https://basarat.gitbooks.io/typescript/docs/types/index-signatures.html). During the tests I'll have a better example.

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [x] Ran `$ yarn lint-all` and fixed all formatting issues
- [x] Ran `$ yarn test-all` and all tests passed
- [ ] Added measurement instrumentation (Mixpanel, etc.)
- [X] Wrote an automated test covering new functionality

2018-05-09 10:23 UTC, tsortwehttam commented on packages/@haiku/core/api/HaikuBytecode.ts
> +  attributes: {[attribute: string] : string;
Note: `source` and `identifier` are legacy and have changed to `haiku-source` and `haiku-var`.

We probably also want to add all of these: https://github.com/HaikuTeam/mono/blob/bfbdce8835c12dfb9f6c3165c58ed046fa781555/packages/haiku-serialization/src/bll/Template.js#L31

2018-05-09 10:23 UTC, tsortwehttam commented on packages/@haiku/core/api/HaikuBytecode.ts
> +  [stateName: string] : {value: string | {text: string}[] };
A state value can be any JSON type (`string`, `boolean`, `object`, `array`, `null`).

2018-05-09 10:26 UTC, tsortwehttam commented on packages/@haiku/core/api/HaikuBytecode.ts
> +  [stateName: string] : {value: string | {text: string}[] };
A state may also have the keys:
- `setter` (fn)
- `getter` (fn)
- `access` (string)
- `type` (string)

2018-05-09 10:27 UTC, tsortwehttam commented on packages/@haiku/core/api/HaikuBytecode.ts
> +  [eventName: string]: {handler: (any) => any};
Not sure if this would belong in the typing or not, but _at runtime_ the render system may add a `.original` function to keep track of the function signature and body prior to being wrapped. See here: https://github.com/HaikuTeam/mono/blob/bfbdce8835c12dfb9f6c3165c58ed046fa781555/packages/%40haiku/core/src/HaikuComponent.ts#L1035

2018-05-09 10:28 UTC, tsortwehttam commented on packages/@haiku/core/api/HaikuBytecode.ts
> +  value: (boolean | string | ((any) => string));
A timeline value can also be any valid JSON type, including `number`, `object`, `array`, `null`.

2018-05-09 10:29 UTC, tsortwehttam commented on packages/@haiku/core/api/HaikuBytecode.ts
> +  branch?: string;
`player` is legacy.

2018-05-09 10:29 UTC, tsortwehttam commented on packages/@haiku/core/api/HaikuBytecode.ts
> +  properties?: HaikuProperties[]
`properties` is legacy.

2018-05-09 23:35 UTC, stristr commented on packages/@haiku/core/api/HaikuBytecode.ts
> +
Hmmm, why do this?

These curves are used extensively in `haiku-formats` and I didn't see a commit fixing that code.

Additionally, although the linter doesn't enforce this (yet), I had been adopting the convention that enum keys should begin with Capital Letter For Emphasis.

2018-05-09 23:37 UTC, stristr commented
Hey, heads up (@jonaias)—I changed the base branch to `rc-mc-group-highlight`. Would you mind rebasing to it and force pushing to get clean history?

```
git fetch
git rebase origin/rc-mc-group-highlight
```

2018-05-09 23:39 UTC, stristr commented on packages/@haiku/core/api/HaikuBytecode.ts
> +  properties?: HaikuProperties[]
Suggestion for deprecated properties: don't type them but do keep them in for formal correctness, with JSDoc `@deprecated` symbol.

e.g.

```
  /**
   * @deprecated
   */
  properties?: any[]
```

2018-05-10 06:34 UTC, jonaias commented on packages/@haiku/core/api/HaikuBytecode.ts
> +  attributes: {[attribute: string] : string;
As both haiku-source and haiku-var are string indexes, they are included by string index signature type ([attribute: string] : string). Added deprecated comment

2018-05-10 06:34 UTC, jonaias commented on packages/@haiku/core/api/HaikuBytecode.ts
> +  [stateName: string] : {value: string | {text: string}[] };
I defined a type `HaikuStateTypes` to be used as state value type.  Added missing state keys.

2018-05-10 06:34 UTC, jonaias commented on packages/@haiku/core/api/HaikuBytecode.ts
> +  [eventName: string]: {handler: (any) => any};
You are right. As we discussed, bytecode typing is only considered on compile time, so it won't be necessary until we start adding types across all code base. For example, to add a .original function, if bytecode is HaikuBytecode, you should add this function as optional to HaikuBytecode.

I'm really excited to start using types everywhere!! I think i will save a large amount of time for us in the future!! On any new feature or refactoring, the compiler will help us =)

2018-05-10 06:34 UTC, jonaias commented on packages/@haiku/core/api/HaikuBytecode.ts
> +  branch?: string;
Added deprecated comment

2018-05-10 06:34 UTC, jonaias commented on packages/@haiku/core/api/HaikuBytecode.ts
> +  properties?: HaikuProperties[]
@stristr thanks for suggestion, i'm adopting it.

2018-05-10 06:34 UTC, jonaias commented on packages/@haiku/core/api/HaikuBytecode.ts
> +
> Hmmm, why do this?

Don't worry its a very ugly temporary solution. The deal is because ["Keep in mind that string enum members do not get a reverse mapping generated at all."](https://www.typescriptlang.org/docs/handbook/enums.html#enums-at-runtime), we cannot use string enum as type of curve `HaikuTimelineValue` attribute:
``` Typescript
export type HaikuTimelineValue = {
  value: (boolean | string | number | ((any) => HaikuStateTypes));
  edited?: boolean;
  curve?: keyof typeof Curve;  // <<<<<<<<<<HERE we cannot use old Curve definition eg. `curve?: Curve`
};
```
A way better explanation is given by [There's some oddities (perhaps bugs?) with how the enum is type checked, its not just a string literal type shorthand, which is what would be truly correct. Some issues I've bumped into](https://stackoverflow.com/q/35760096/1524655). And in our case, we use curve names from bytecode as string.

For now, I see two possible solutions
- Rename bytecode curve names to Capital Letter. eg. on bytecode file `curve: 'EaseOutSine'` instead of `curve: 'easeOutSine'`   (con: it will break compatibility)
- Use [String Literal Types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#string-literal-types) only for bytecode type definition. eg  `type CurveType = "easeInBack" | "easeInCirc" | "easeInCubic"..` and keep them in sync with Curve definition (con: need to keep in sync Curve and CurveType )

I'm not happy with these solutions, so i'll come back latter to this. Maybe I can find better solution.

2018-05-10 17:37 UTC, stristr commented on packages/@haiku/core/api/HaikuBytecode.ts
> +
Just to keep "eye on the prize" here: I think for now, a perfectly suitable type for `curve?:` is simply `string`. We want to support arbitrary bezier curves, spring transitions, and more in the near future—and in order to do that, it should be clear that the "string" version soon to be extended to include `{x1: number, y1: number, x2: number, y2: number}` (one way to represent arbitrary beziers), `{tension: number, friction: number, velocity: number}` (one way to represent arbitrary springs)…and along the way, we might want users to be able to make a "curve library", give a custom curve a name like `"myCustomCurve"`, and refer to it by name (`"curve": "myCustomCurve"`). It might be a bezier, or a spring, or an arbitrary function `f(t): [0, 0] -> [1, 1]`…better IMO to not constrain this now, especially since it's a single field and the relevant type is a curve.

One other bit of related advice: we need to keep `@haiku/core` dependency free and open source, so nothing in `packages` outside of `packages/@haiku/core` is really fair game for including as a dependency unless we plan to open source it. Even though you technically _can_ import files from `haiku-common` into `@haiku/core` and use its types, the typing file `(.d.ts`) that comes out will confuse compilers in other TypeScript projects that use `@haiku/core` as a direct dependency. So for now, all typings that exist in other packages that you might want to use here should be moved into `@haiku/core`. `Curve` probably isn't one that you want or need, but in case there are others 😉 ….

2018-05-10 17:58 UTC, jonaias commented on packages/@haiku/core/api/HaikuBytecode.ts
> +
I was thinking about moving Curve to @haiku/core.. but with your explanation cleared things.  Thanks.

Sure, when other curve types are implemented, we can change it from string to exactly possible curve types.

2018-05-11 01:18 UTC, stristr commented
BUILDME!

2018-05-11 05:01 UTC, stristr requested changes
Nice progress! :+1:

Someday, I would like to turn on the `"noImplicitAny"` config option in `tsconfig.json`. If you do that now, you'll notice that there are errors all over—ideally, this PR will reduce those errors wherever bytecode and things "beneath" bytecode are found, so I think there's still quite a bit of work to be done here to trace the types where they go. I mentioned `haiku-formats` as a good testing ground for how complete this work is because it's a much smaller code base where you _could_ turn on `"noImplicitAny"`, delete all the lazy `any` types in the `haiku-formats` package, apply the `HaikuBytecode` type, and see what happens. It's still important to carefully trace the path of bytecode through the `HaikuComponent` constructor and down to all the other things that happen with `this.bytecode`. As you go, strike out bytecode-descended things that are explicitly or implicitly typed as `any` and replace them with their actual types.

Some examples from the constructor `bytecode.template = xmlToMana(bytecode.template);`—so `xmlToMana` is a function that needs to accept `string` and return `BytecodeTemplate`. So go type its arguments, and the methods it calls, and come back and make sure everything still compiles.

A more complex example is:

```
  eachEventHandler (iteratee: Function) {
    if (this.bytecode.eventHandlers) {
      for (const eventSelector in this.bytecode.eventHandlers) {
        for (const eventName in this.bytecode.eventHandlers[eventSelector]) {
          iteratee(
            eventSelector,
            eventName,
            this.bytecode.eventHandlers[eventSelector][eventName],
          );
        }
      }
    }
  }
```

Okay, so `iteratee` isn't really just any function…it's really an `(eventSelector: string, eventName: string, handler: BytecodeEventHandler) => void`! To be thorough, we should make sure everything that calls `eachEventHandler` works with this type.

In general, trace what happens to `this.bytecode` inside `HaikuComponent.ts`, type the related methods, and come back and make sure everything still compiles. `HaikuComponent.ts` constructor was meant to be a starting point for finding all the places we should be applying types to flesh out and validate the API, but not the only place where we apply the related types.

2018-05-11 05:01 UTC, stristr commented on packages/@haiku/core/test/TestHelpers.js
>  const HaikuDOMRenderer = require('../lib/renderers/dom').default;
Some inconsistent style here—note use of `"` instead of `'` and commented out code, etc.

Request, since I was going to do this anyway: as part of this branch, would you please convert our test suite to TypeScript, and add a script for linting it with the linter (e.g. `yarn test-lint`)? There are 33 test files, so shouldn't be a huge amount of work, and it would really help move the TypeScript project forward. There's a good reference for how to write `tape` tests using TypeScript in `packages/haiku-formats` you can imitate.

2018-05-11 05:01 UTC, stristr commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +/**
Please note changes made in 4db9003fa7c967a53264624fca0b67ec864971ac here. There are some things missing in `tslint-config-haiku` I'll be adding later next week.

2018-05-11 05:01 UTC, stristr commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +  [eventName: string]: {handler: (any) => any};
Let's definitely improve this `(any) => any` 😃.

These are all `(component: HaikuComponent, event: Event, ...args: any[]) => void`…I think.

Similar to the `PrimitiveType` above, definitely want to export a `BytecodeEventHandler` type, which will come up elsewhere….

2018-05-11 05:01 UTC, stristr commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +  [elementName: string]: BytecodeEventHandler;
These aren't really `elementName`s, but `eventSelector`s.

Note/nit: since it's better to have no name than a wrong name, feel free to stick with the simpler `[key in string]: BytecodeEventHandler ` when it makes sense to do so.

2018-05-11 05:01 UTC, stristr commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +  [propertyName: string]: {[key in string]: BytecodeTimelineValue};
Note edit I made in 4db9003fa7c967a53264624fca0b67ec864971ac here: when a "`number`" is a key of a JS object, it's really a string masquerading as a number. Although TypeScript lets you type it the way you had it (and the ES6 `Map<T, U>` type actually lets you type it the way we _want_ it 😸), "number keys of plain objects" are not really a thing.

2018-05-11 05:01 UTC, stristr commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +  properties?: BytecodeProperties[];
Given that this is fully deprecated, `BytecodeProperties` is also fully deprecated, and (FWIW) `any[]` would be perfectly suitable here.

2018-05-11 05:01 UTC, stristr commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +  options?: any
This is not `any`, but (@matthewtoast please correct me if I'm wrong) an instance of `typeof DEFAULTS` as found in `Config.ts`. This should also get a type.

2018-05-11 05:01 UTC, stristr commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +  value: (boolean|string|number|((any) => BytecodeStateType));
Similar to `BytecodeEventHandler`, these are very special functions, always the result of calling `Haiku.inject` (`HaikuInjectedFunction`)? And the way we call `Haiku.inject` is very special too: `Haiku.inject(expressionHandler: (...args: HaikuInjectable[]) => PrimitiveElement, ...argNames: string[])`, so as part of typing bytecode we should trace the peripheral behaviors of `Haiku.inject`.

`HaikuInjectable` is a union type `BytecodeStateType|HaikuSummonable`, where `HaikuSummonable` is yet another type 💃!!!

Look for `INJECTABLES['$user']`, `INJECTABLES['$element']`, etc. to see how these work.

2018-05-11 05:10 UTC, stristr commented on packages/@haiku/core/test/api/05_HaikuTypes.test.js
> +  const nonConformantBytecodeFiles = [
Note: these non-conformant bytecode files are actually supported by our "in-place migration" procedure that happens inside `Migration.ts`. You should be able to trigger and fix the related compiler errors (through additional typing) by explicitly using the `HaikuBytecode` type on `component.bytecode` in `Migration.ts:runMigrations`.

2018-05-11 07:39 UTC, jonaias commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +/**
That will be very useful.

2018-05-11 07:39 UTC, jonaias commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +  [eventName: string]: {handler: (any) => any};
As they involve typing from elsewhere (HaikuComponent, Event, etc), i think it might be better to add these types later (even create other files under api/ to move some types there) , when starting adding types to HaikuComponent. 

I know from some tests I did, HaikuBytecode isn't complete to be used everywhere (I set the type of bytecode HaikuComponent to HaikuBytecode, and there are some fields that are add to be used in runtime only).

One idea is to have a property under HaikuBytecode called for example `runtime`, so every added runtime objects would stay under this property.

2018-05-11 07:39 UTC, jonaias commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +  [elementName: string]: BytecodeEventHandler;
Thanks, changed it to eventSelector.

One thing I noticed when adding typing to haiku-formats is that BytecodeTemplate would be better as BytecodeNode.

2018-05-11 07:39 UTC, jonaias commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +  [propertyName: string]: {[key in string]: BytecodeTimelineValue};
Nice info! I will update it to be a string.

2018-05-11 07:39 UTC, jonaias commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +  properties?: BytecodeProperties[];
:+1:

2018-05-11 07:39 UTC, jonaias commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +  options?: any
I'll put in TODO list for this PR

2018-05-11 07:39 UTC, jonaias commented on packages/@haiku/core/test/TestHelpers.js
>  const HaikuDOMRenderer = require('../lib/renderers/dom').default;
Sounds a nice improve using only typescript for testing, I can do this tomorrow.

2018-05-11 07:39 UTC, jonaias commented on packages/@haiku/core/test/api/05_HaikuTypes.test.js
> +  const nonConformantBytecodeFiles = [
I'll check it tomorrow. (notice that I suppose the migration occurs in runtime and this test is compile time only)

2018-05-11 07:39 UTC, jonaias commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +  value: (boolean|string|number|((any) => BytecodeStateType));
I saw this type being used in `packages/haiku-formats/src/exporters/injectables.ts` function `evaluateInjectedFunctionInExportContext`.

2018-05-11 07:52 UTC, jonaias commented
Back to WIP. My TODO list:
 [] - Add options correct type
 [] - Transform tests in TS only
 [] - Check about typings of  HaikuSummonable/EventHandler
 [] - Check about using migration.ts to test typing on non conformant bytecodes

2018-05-11 17:52 UTC, stristr commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +  [elementName: string]: BytecodeEventHandler;
Yeah, I agree with that being a better name for the type.

2018-05-11 18:04 UTC, stristr commented
Sounds good! Please layer into TODO list:
 - [ ] Enable `"noImplicitAny"` in `packages/haiku-formats/tsconfig.json`, remove all `any` types, and fix lint errors.
 - [ ] Per above, carefully trace the path of bytecode through the `HaikuComponent` constructor and down to all the other things that happen with `this.bytecode`. As you go, strike out bytecode-descended things that are explicitly or implicitly typed as any and replace them with their actual types.

2018-05-14 06:54 UTC, jonaias commented
- [x] Add options correct type
- [x] Transform `@haiku/core test` into TS only
  -  An interesting fact, the test `core/test/unit/reflection.functionToRFO.test.js` wasn't converted because typescript compile scrambles function comments on transpilation. To make our test suite simpler, the `reflection.functionToRFO.test.ts`, calls .js test, enabling it also being considered a TS test
- [x] Check about typings of HaikuSummonable/EventHandler
  - HaikuSummonable was implemented. EventHandler wans't used by `haiku-formats`, so I preferred not to implement it
- [x] Check about using migration.ts to test typing on non conformant bytecode
   - It would be lot of trouble to mix compile time and runtime test, I opted to avoid it. (Migration itself should be covered by its tests)
- [x] Enable `noImplicitAny` in packages/haiku-formats/tsconfig.json, remove all any types, and fix lint errors.
   - DONE!! :metal: :metal:.  Note that  some `haiku-formats` functions (generally ones interfacing BodyMoving, there wasn't typescript already made definitions - DefinitelyTyped -, so I left some of them as any)
- [ ] Per above, carefully trace the path of bytecode through the HaikuComponent constructor and down to all the other things that happen with this.bytecode. As you go, strike out bytecode-descended things that are explicitly or implicitly typed as any and replace them with their actual types
   - Wasn't able to fix types in available time.

2018-05-15 05:25 UTC, jonaias commented
BUILDME!

2018-05-15 22:35 UTC, stristr reviewed
Looking very nice!

Just a few additional change requests here, and this should be good to merge later today 👍.

2018-05-15 22:35 UTC, stristr commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +  frame?: (() => void)|null,
Question: is the `|null` union type necessary here? I believe the `?` means "nullable", so `|null` is unnecessary here and below.

2018-05-15 22:35 UTC, stristr commented on packages/@haiku/core/package.json
> +    "cross-env": "^5.1.4",
Hmmm, why is this dependency added here? It doesn't seem to be used anywhere.

2018-05-15 22:35 UTC, stristr commented on packages/@haiku/core/package.json
> +    "test-report": "tape \"~test/**/*.test.js\" > test-result.tap",
Couple of things:

1. Let's go ahead and make just one `yarn test` command that only compiles once (`tape "~test/**/*.test.js"`). Will be doing this across other projects with multiple "suites" set up like this. No need for `test:perf`, …, `test:unit`….
2. Let's also have one `yarn lint` which lints both source files and tests in a single command.
3. Let's clean up `~test` after running tests, like the `rm -rf ~test` in `haiku-formats`…
4. …and in case something crashes, please add `~test` to `.gitignore` so it doesn't sneak into source control.

2018-05-15 22:35 UTC, stristr commented on packages/@haiku/core/src/Layout3D.ts
> +export type LayoutSpecType = {
Nit/naming: it seems a bit extra to call a type for "thing that is a layout spec" `LayoutSpecType`. `LayoutSpec` is a better, more concise name. See also: `BytecodeStateType` (maybe `BytecodeStateValue` is better?)….

We could even change `PrimitiveType` to `Primitive` or similar, come to think of it.

Also: I would like to move this and all additional typings to the `src/api` "namespace" for future plans.

2018-05-15 22:35 UTC, stristr commented on packages/@haiku/core/test/TestHelpers.ts
> +const jsdom = require('jsdom');
To complete the migration to TypeScript, we should rewrite all `require()` statements as `import` statements.

Please don't do this now; just filing a note for later.

2018-05-15 22:35 UTC, stristr commented on packages/haiku-formats/src/exporters/bodymovin/bodymovinTypes.ts
> +// TODO: It is commented due: https://github.com/Microsoft/TypeScript/issues/13042,
Actually, this should work using:

```
[key in TransformKey.TransformOrigin]: {…}
```
etc.

That specific issue is about using `index in` typing for integer enums. String enums should be fine with `key in` typing.

2018-05-15 22:35 UTC, stristr commented on packages/haiku-formats/package.json
> +    "@types/bluebird": "^3.5.20",
Hmm…why is `@types/bluebird` added here when `bluebird` is not a direct (dev or non-dev) dependency of `haiku-formats`? I think the places it needs to be added are the dependencies `bluebird` is coming from. (Use `yarn why bluebird` to see where it's coming from.)

This happens to work because of how everything is set up using yarn workspaces, but in isolation, this dependency is in the "wrong place".

2018-05-15 22:35 UTC, stristr commented on packages/haiku-formats/src/exporters/bodymovin/bodymovinExporter.ts
> +
[See 9106dd832 for the solution to the problem solved temporarily here]

2018-05-16 03:31 UTC, jonaias commented on packages/@haiku/core/src/api/HaikuBytecode.ts
> +  frame?: (() => void)|null,
If I understood correctly, according to "Optional parameters and properties" from, https://www.typescriptlang.org/docs/handbook/advanced-types.html, ? means "undefinable".

Anyway, I agree with you... It is much better left it "undefinable" than "nullable".

2018-05-16 03:32 UTC, jonaias commented on packages/@haiku/core/package.json
> +    "cross-env": "^5.1.4",
yep, removed it

2018-05-16 03:33 UTC, jonaias commented on packages/@haiku/core/package.json
> +    "test-report": "tape \"~test/**/*.test.js\" > test-result.tap",
Accept your challenge (and suggestion) and now we are using ts-node. As you forecasted, it was pretty straightforward.

2018-05-16 03:52 UTC, jonaias commented on packages/@haiku/core/src/Layout3D.ts
> +export type LayoutSpecType = {
I agree with LayoutSpecType, very redundant, fixed it.. About BytecodeStateType, if we change to BytecodeStateValue, it could means its value instead its type, idk..

2018-05-16 03:55 UTC, jonaias commented on packages/haiku-formats/package.json
> +    "@types/bluebird": "^3.5.20",
Fixed it.. the indirect dependency was `haiku-sdk-creator`.

2018-05-16 04:09 UTC, jonaias commented on packages/@haiku/core/test/TestHelpers.ts
> +const jsdom = require('jsdom');
Some of them are related to https://github.com/HaikuTeam/mono/commit/9106dd832d9b0ad0339a063d56e297a1e05b1239.  Ok.

2018-05-16 04:18 UTC, jonaias commented on packages/haiku-formats/src/exporters/bodymovin/bodymovinExporter.ts
> +
:+1:

2018-05-16 04:54 UTC, jonaias commented on packages/haiku-formats/src/exporters/bodymovin/bodymovinTypes.ts
> +// TODO: It is commented due: https://github.com/Microsoft/TypeScript/issues/13042,
I thought the last reply in the commented link (a PR closing the issue) would enable something like [key in keyof TransformKey]. Or at least make commented code work.

Accepted the suggestion.

2018-05-16 17:09 UTC, stristr commented on packages/haiku-formats/src/exporters/index.ts
> +import * as LoggerInstance from 'haiku-serialization/src/utils/LoggerInstance';
:+1:, sorry about that!

2018-05-16 17:17 UTC, stristr commented
Please note changes in 507558922e40f59e2cdaefc91ae8c4d19e5dc8fa:
 - [nit] removed some redundant usages of `yarn` in command specs.
 - [important] access `tape` binary at `./node_modules/.bin/tape` instead of `../../../node_modules/tape/bin/tape`. The reason for this is `@haiku/core` is an [open source repository](https://github.com/HaikuTeam/core) that people should be able to pull and contribute to like any other, but `mono` is not. The only reason you find the `tape` binary at that location is the way we're using [Yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) in `mono` specifically. The symlink from `./node_modules/.bin/tape` -> `../../../../../node_modules/tape/bin/tape` -> `../../../node_modules/tape/bin/tape` will work in both contexts.

2018-05-16 17:17 UTC, stristr commented
LGTM! Very, very nice work here 👍 😺 🥇!

Merging.

2018-05-16 17:17 UTC, stristr approved these changes

2018-05-16 17:17 UTC, merged