Raw code editor
HaikuTeam/animator pull request #500
Opened 2018-05-29 07:30 UTC by jonaias

OK to merge.

Short review.

Summary of changes:

 - Implemented raw code editor. Design spec: https://haiku.quip.com/pLmCAnw3uCzY

Notes for reviewers:

 - Not sure if css transitions (haiku-creator/src/react/components/Stage.js) is implemented in the most clean way.

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [ ] Added measurement instrumentation (Mixpanel, etc.)
- [ ] Wrote an automated test covering new functionality

2018-06-04 06:01 UTC, jonaias commented
Code editor working:
![peek 2018-06-04 02-52](https://user-images.githubusercontent.com/800493/40900610-bfdc5632-67a2-11e8-884e-a3dc0ffaa666.gif)

Checking if bytecode can be required before saving.
![peek 2018-06-04 02-57](https://user-images.githubusercontent.com/800493/40900676-14ef3810-67a3-11e8-9109-bb7c698aed56.gif)

I had a lot of troubles with race conditions while implementing save file. Had to start over more than once. I'm happy with resulting implementation (Much cleaner than I expected)

2018-06-04 11:27 UTC, tsortwehttam requested changes

2018-06-04 11:27 UTC, tsortwehttam commented on packages/haiku-creator/src/react/components/CodeEditor/CodeEditor.js
> +      this.props.projectModel.on('update', (what, ...args) => {
We probably need to unsubscribe from this event to prevent multiple subscriptions: Consider what happens when:

1. User opens project A
2. User navigates back to dashboard
3. User opens project B
4. User navigates back to dashboard
5. User opens project A again

2018-06-04 11:27 UTC, tsortwehttam commented on packages/haiku-creator/src/react/components/CodeEditor/CodeEditor.js
> +  componentWillMount () {
Should this be `componentDidMount` (to avoid `Cannot call setState on unmounted component` errors)?

2018-06-04 11:27 UTC, tsortwehttam commented on packages/haiku-creator/src/react/components/CodeEditor/CodeEditor.js
> +    // Force module reload
Can you document why forcing a reload is needed here?

2018-06-04 11:27 UTC, tsortwehttam commented on packages/haiku-creator/src/react/components/CodeEditor/MonacoEditor.js
> +    this.__current_value = props.value
Nit: Rename to `this.currentValue`, `this.preventTriggerChangeEvent`?

2018-06-04 11:27 UTC, tsortwehttam commented on packages/haiku-creator/src/react/components/CodeEditor/MonacoEditor.js
> +    if (typeof this.editor !== 'undefined') {
Nit: This could probably just be `if (this.editor) { ... }`

2018-06-04 11:27 UTC, tsortwehttam commented on packages/haiku-creator/src/react/components/StageTitleBar.js
> +        {this.isEventHandlersEditorAvailable() &&
👍

2018-06-04 11:27 UTC, tsortwehttam commented on packages/haiku-serialization/src/bll/ActiveComponent.js
> +        console.log('HardReload on ', this.project.getAlias(), ', file:', this.fetchActiveBytecodeFile().relpath)
If you want to keep this log, use `logger.info(...)` here instead. (We might want to remove it for `softReload` since that happens a lot.)

2018-06-04 11:27 UTC, tsortwehttam commented on packages/haiku-serialization/src/bll/ModuleWrapper.js
> +  var paths = Module._nodeModulePaths(path.dirname(filename))
Nit: Avoid all use of `var` and please use `let`/`const` instead.

2018-06-04 11:27 UTC, tsortwehttam commented on packages/haiku-serialization/src/bll/ModuleWrapper.js
> +ModuleWrapper.requireFromString = (code, filename, opts) => {
We have very similar functionality written here: https://github.com/HaikuTeam/mono/blob/master/packages/haiku-creator/src/react/components/ProjectPreview.js#L14 (Please especially note L23-25) Maybe we should consolidate the other logic to use your method?

2018-06-04 11:36 UTC, tsortwehttam commented
@jonaias I'm going to review the functionality locally. If I find bugs I will just file them in Asana instead of in here, ok?

2018-06-04 11:49 UTC, tsortwehttam commented
Did some brief, general testing of the feature. The full team should QA it this week, but it works pretty well for me 👍 It's really cool to (e.g.) edit values in the timeline and see them change in the code, and vice-versa. 🎆 I filed a few small bugs in Asana.

2018-06-05 07:18 UTC, jonaias commented on packages/haiku-creator/src/react/components/CodeEditor/CodeEditor.js
> +  componentWillMount () {
:+1:

2018-06-05 07:18 UTC, jonaias commented on packages/haiku-creator/src/react/components/CodeEditor/CodeEditor.js
> +      this.props.projectModel.on('update', (what, ...args) => {
You are right. Fixing it.

2018-06-05 07:18 UTC, jonaias commented on packages/haiku-creator/src/react/components/CodeEditor/CodeEditor.js
> +    // Force module reload
Nice spot. This was one of race conditions while switching currently active component.

2018-06-05 07:18 UTC, jonaias commented on packages/haiku-creator/src/react/components/CodeEditor/MonacoEditor.js
> +    this.__current_value = props.value
:+1:

2018-06-05 07:18 UTC, jonaias commented on packages/haiku-creator/src/react/components/CodeEditor/MonacoEditor.js
> +    if (typeof this.editor !== 'undefined') {
:+1:

2018-06-05 07:18 UTC, jonaias commented on packages/haiku-serialization/src/bll/ActiveComponent.js
> +        console.log('HardReload on ', this.project.getAlias(), ', file:', this.fetchActiveBytecodeFile().relpath)
I intentionally left there because as softReload and hardReload are *very* expensive functions, always printing them make pretty clear they are being executed, and in the future might bother someone to remove some unnecessary reload calls. 

About softReload, I'd also like them.

2018-06-05 07:18 UTC, jonaias commented on packages/haiku-serialization/src/bll/ActiveComponent.js
> +        console.log('HardReload on ', this.project.getAlias(), ', file:', this.fetchActiveBytecodeFile().relpath)
BTW, someone talked about some logging facilities on team call.. Something along the lines of android log tags `Log.v("tag", "message");` (they can be enable/disable according to tag) would be very helpful to debug and develop. Just a thought..

2018-06-05 07:18 UTC, jonaias commented on packages/haiku-serialization/src/bll/ModuleWrapper.js
> +ModuleWrapper.requireFromString = (code, filename, opts) => {
The 'your' is too much ehheheh I copied from https://github.com/floatdrop/require-from-string, left the comment there to honor the correct author. Yep, we might use this method instead.

I'll test if everything works correctly.

2018-06-05 07:18 UTC, jonaias commented on packages/haiku-serialization/src/bll/ModuleWrapper.js
> +  var paths = Module._nodeModulePaths(path.dirname(filename))
:+1:

2018-06-05 07:46 UTC, jonaias commented
Using requireFromString to load project miniatures works!.  I rebased and cleaned commit history.

2018-06-05 13:58 UTC, stristr commented on packages/haiku-serialization/src/bll/ModuleWrapper.js
> +ModuleWrapper.requireFromString = (code, filename, opts) => {
See also `packages/haiku-creator/src/react/components/ProjectPreview.js`. Can we consolidate here?

2018-06-05 14:00 UTC, stristr commented on yarn.lock
> +
Looks like this PR brings in an additional copy of `monaco-editor`. Can you please be sure to align the dependency version? This could either be by downgrading the version you added to `haiku-creator` or by upgrading the version in `haiku-glass` (both probably require testing if there are breaking API changes).

2018-06-05 15:48 UTC, jonaias commented on yarn.lock
> +
I took a look at monaco-editor changelog.. We don't use any of breaking changes. Updated it.

2018-06-05 15:51 UTC, jonaias commented on packages/haiku-serialization/src/bll/ModuleWrapper.js
> +ModuleWrapper.requireFromString = (code, filename, opts) => {
Sorry I didn't follow. By consolidating you mean using this same method on `packages/haiku-creator/src/react/components/ProjectPreview.js`? 

If so, Matthew also mentioned it, implemented in aa7c0efe96b1d12b792d897c0ed4a673f8f3efbb.

2018-06-05 15:58 UTC, stristr commented on packages/haiku-serialization/src/bll/ModuleWrapper.js
> +ModuleWrapper.requireFromString = (code, filename, opts) => {
Yep! Sorry, missed that.

2018-06-06 12:05 UTC, tsortwehttam approved these changes

2018-06-07 11:28 UTC, tsortwehttam commented
Code LGTM, merging into `rc-3.5.0`.

2018-06-07 11:28 UTC, merged

2018-06-08 17:27 UTC, stristr commented on packages/haiku-creator/src/react/components/CodeEditor/CodeEditor.js
> +    activeComponent.fetchActiveBytecodeFile().flushContentFromString(currentEditorContents)
Will need to fix.

 - Leaky abstraction—no way should a content flush be happening from React.
 - More importantly, nothing other than `Master`-controlled AC should be triggering a writeout because the filesystem lock used for all other writeouts would not apply here. We'll need to handle this via IPC.