Making movies
HaikuTeam/animator pull request #579
Opened 2018-06-26 22:53 UTC by stristr

OK to merge.

Short review.

Summary of changes:

- Basic functionality for exporting variable framerate GIFs and H.264 videos on-demand, all hidden behind an experiment flag.

Regressions to look for:

- None expected—although there is significant refactoring to the entry point for `haiku-formats` exporting. Suffices to confirm that on publish, `lottie.json` is written out (I have already done this).

Notes to reviewers:
 - The `ffmpeg` solution involves bringing in precompiled binaries via `ffmpeg-static`. (Decided against linking `ffmpeg` directly with a C++ add-on after consultation with @matthewtoast.) That package comes laden with 252MB of precompiled binaries; the expected behavior of the bundling process is to bloat the package size by only the one we're actually using (e.g. `node_modules/ffmpeg-static/bin/*darwin*/*x64*/ffmpeg`). We should make sure that's actually happening (via ad-hoc build) before merging this.

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality

2018-06-26 23:00 UTC, stristr commented
RECHECK!

2018-06-27 00:31 UTC, stristr commented
RECHECK!

2018-06-27 01:33 UTC, stristr commented
RECHECK!

2018-06-27 01:33 UTC, stristr commented
(plz)

2018-06-29 02:30 UTC, stristr commented
BUILDME!

2018-06-29 15:16 UTC, tsortwehttam commented on packages/haiku-creator/oven.html
> +<!doctype html>
Just want to say I appreciate your naming all throughout this diff.

2018-06-29 15:20 UTC, tsortwehttam commented on packages/haiku-creator/src/bakery/electron.ts
> +  const height = bytecode.timelines.Default['haiku:' + haikuId]['sizeAbsolute.y'][0].value;
Due to "auto"-sizing, you may want to test that width/height are actually numeric before continuing. It is possible that a user might want to set their main component to "auto"-size. To compute a size, you should be able to call `HaikuComponent#computeSize` (`HaikuElement#computeSize`) and friends.

2018-06-29 15:26 UTC, tsortwehttam requested changes

2018-06-29 15:26 UTC, tsortwehttam commented on packages/haiku-plumbing/src/Watcher.js
> +      ignored: /(node_modules|bower_components|jspm_modules|\.git|~\.sketch|png\/*)/,
Maybe change the ignore pattern from `png` to `code/*/*.png` or whatever the destination folder of the PNGs is? We shouldn't exclude _all_ pngs. (In the near future, users will be able to import image assets and instantiate them; for that to work with our asset listing logic, we'll need the watcher to be aware of them.)

2018-06-29 15:27 UTC, tsortwehttam commented
Overall code looks good. Only one or two specific issues I think needs to be addressed before merging.

2018-06-29 15:29 UTC, tsortwehttam commented
@stristr -- I wonder if any of this logic could be reused for sake of component thumbnails? https://app.asana.com/0/713061630135205/686777755217976 I haven't thought much about how I'm going to implement, but grabbing a tiny PNG of the component seems at least one plausible way.

2018-06-29 17:21 UTC, stristr commented on packages/haiku-creator/oven.html
> +<!doctype html>
Thank you! Also the name of this PR is a Talking Heads album. Also my prior statement is also a Talking Heads album reference.

2018-06-29 17:38 UTC, stristr commented on packages/haiku-plumbing/src/Watcher.js
> +      ignored: /(node_modules|bower_components|jspm_modules|\.git|~\.sketch|png\/*)/,
Ah, so glad you mentioned. This _was_ already done to a point (`png/` was excluded, not `png`), but I later changed the directory pattern to be `png-${framerate}` and hadn't refactored this.

Anyway, changing as requested to both be correct and trap the ignore pattern inside of a component folder.

2018-06-29 17:40 UTC, stristr commented on packages/haiku-creator/src/bakery/electron.ts
> +  const height = bytecode.timelines.Default['haiku:' + haikuId]['sizeAbsolute.y'][0].value;
Oof. Is this going to be a big problem for Lottie? Right now we do Lottie 100% server side, without a hot rendered component instance to give up the goods. Does this method always work without a window? Or do we need Glass/someone to transmit size on export requests now?

2018-06-29 20:38 UTC, stristr commented
@matthewtoast this should be good to go.

638699e is a major refactor (moving `computeLayout` out of `Layout3D`) so please merge when ready.

2018-06-30 14:56 UTC, tsortwehttam approved these changes

2018-06-30 14:56 UTC, merged

2018-06-30 22:18 UTC, stristr commented
Responding to thought about the PNG reuse for component thumbnails—we _could_, but wouldn't a full (overlaid) render of the component on hover be both sufficient and more awesome?