Zen
HaikuTeam/animator pull request #639
Opened 2018-07-29 02:58 UTC by stristr

OK to merge.

Short review.

Summary of changes:

- A smorgasbord of perf-targeting changes.
- [x] Do not initialize layout when it is not needed.
- [x] Do not set width when it doesn't do anything.
- [x] Keep `cachedTransform` in memory instead of using `isEqualTransformString`.
- [x] Optimize patch routine.

Regressions to look for:

- Check demos carefully :smile:

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [ ] Wrote an automated test for existing and modified functionality

2018-07-29 02:59 UTC, stristr commented
(flaky test failures expected)

2018-07-29 09:24 UTC, stristr commented on packages/@haiku/core/src/HaikuComponent.ts
> +        const propertiesGroup = mutableTimelineDescriptor[behaviorSelector];
@matthewtoast…I feel like we discussed this line of code and you said "I realize this is wrong, but weird things started to happen when it wasn't there." Can you check if this is still the case? It's working fine for me.

2018-07-29 09:43 UTC, stristr commented
WIP stats from this branch re: core perf, looking at share.haiku.ai front page for reference:
- In prod, share-page is running at 60 FPS.
- On `master`, share-page is running at 28 FPS.
- On `zen`, share-page is running at 48 FPS.

Still a lot of room for improvement, but I think we should merge this chunk of work ASAP.

2018-07-29 16:29 UTC, tsortwehttam commented on packages/@haiku/core/src/renderers/dom/assignStyle.ts
> -      }
Did you check this against `butterblast` perf?

2018-07-29 17:05 UTC, tsortwehttam requested changes
Overall good changes and I can feel the perf difference when running locally.

A few things are broken in the demos that will need to be resolved:

  - shadows/blurs:
    - ShadNo
    - InTheSpace
    - comet-rotation
    - drop-shadow
    - filter-instances
    - mc-blur-shadow

  - offset/origin
    - cardmenu
    - heartstry4 [*and all demos that use it, incl. react-*]
    - moto7

  - auto-preserve-3d
    - threedee-perspective-just-work [see the .png in the folder for reference]

  - box size
    - clickable-square [interestingly, a red square now displays in this demo]
    - controlflow-placeholder-* [the spans are now half their original height]

2018-07-29 17:05 UTC, tsortwehttam commented on packages/@haiku/core/src/HaikuComponent.ts
> +    withLayout(element, () => {
Vanities are _very_ hot, and ideally we should keep them minimal in terms of CPU and especially garbage creation. (The way this is written, we will be creating a lot of `()=>{}` every frame.) My preference would be to move `withLayout` call back into `hydrateNode` where it used to be part of `initializeNodeAttributes` which is called before properties are applied. Is there any reason we can't/shouldn't do that?

2018-07-29 17:05 UTC, tsortwehttam commented on packages/@haiku/core/src/layout/applyCssLayout.ts
> +};
I see the MDN doc link, but note that all elements with `display: block` or `display: inline-block` do respond to to width/height. I wonder if we should check that instead of using this whitelist?

2018-07-29 17:08 UTC, tsortwehttam commented on packages/@haiku/core/src/renderers/dom/assignStyle.ts
> -      }
Answering my own question, I just checked `butterblast` and perf is great. Plays fairly smooth in Chrome even with all three `butterblast` running together. Also this change should fix https://app.asana.com/0/743996399535511/757668381087320

2018-07-29 19:39 UTC, stristr commented on packages/@haiku/core/src/layout/applyCssLayout.ts
> +};
Mmmm, not if they're inside an SVG. You don't think we're capturing all use cases by also whitelisting divs?

I would be okay with doing only these tags in an SVG scope, and all other tags outside an SVG scope. Make sense?

2018-07-29 19:42 UTC, stristr commented on packages/@haiku/core/src/HaikuComponent.ts
> +    withLayout(element, () => {
So, those `()=>{}` are inlined and I don't think they actually create garbage.

But even if they do, I would say no, we really shouldn't do this in `hydrateNode`. The whole point of this optimization is only to set up layout if layout properties are actually applied.

I will instead refactor to:

```
ensureLayout(element);
element.layout.shown = value;
```

etc.

2018-07-30 00:36 UTC, stristr commented
Cool, so re: demos—

- All shadow/blurs and origin/offset issues addressed by 2f09ef6.
- `auto-preserve-3d` was actually broken in master (by me). I fixed it yesterday but hadn't rebased—see 46b23b2.
- under heading "box size", I didn't see any difference between `clickable-square` and `controlflow-placeholder-*` demos between `master` and my branch—are some things also broken in `master` maybe?

About 2f09ef6—it puts the perf issues back on `butterblast` (not better or worse than before). Good news is, I figured out why they're there, and can explain how to fix (without hacking overflow :smile:)!

Would prefer to merge at this commit if you're satisfied and fix it later. Separate doc coming on `butterblast` perf.

2018-07-30 01:00 UTC, tsortwehttam approved these changes

2018-07-30 01:01 UTC, tsortwehttam commented
LGTM.

2018-07-30 15:10 UTC, merged