feat: shells ui
HaikuTeam/animator pull request #759
Opened 2018-08-29 18:34 UTC by roperzh

OK to merge.

Short review.

Summary of changes:

~Implements v0 of shells ui. PR for visibility, but there are still two main problems to solve:~

## ~Leaf nodes (UX pain)~

<details>
  <summary>Click to expand</summary>
~According to the task:~

> for elements that are "effectively leaf nodes", hoist the discovered addressable properties (e.g. color, path) to the element-proper, rather than nesting

~The thing is, if an element has many leaf nodes with the same property we end up in an state like this:~

<img width="303" alt="screen shot 2018-08-29 at 3 29 21 pm" src="https://user-images.githubusercontent.com/4419992/44807588-52f97f80-aba0-11e8-9d7d-daa7c728e42f.png">

</details>

## ~Groups and re-hydration (Bug)~

<details>
  <summary>Click to expand</summary>
~Consider the following case:~

- ~Instantiate 3 `Haiku Icon`s and group them in `Group 1`~
- ~Instantiate `Heart Icon`~
- ~Group `Group 1` with `Heart Icon`, creating `Group 2`~

~you will expect the element tree to be:~

```
Group 2
 Heart Icon
 Group 1
   Heart Icon
   Heart Icon
   Heart Icon
```

~But for some unknown reason it happens to be:~

```
Group 2
   Heart Icon
   Heart Icon
   Heart Icon
```

~Note that this happens at model-level and it's not related to the shells itself.~

~Matthew pointed out a couple of suggestions to look for, and I'm working on it but without any results so far.~
</details>

<br />
<br />

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [ ] Wrote an automated test for existing and modified functionality
- [ ] Added measurement instrumentation (Mixpanel, etc.)
- [ ] Updated `changelog/public/latest.json`

2018-08-29 18:49 UTC, stristr commented
@roperzh, have you tested this with several copies of @jonaias's infamous `Coin_Icon.svg` asset? I have found this asset to be a good benchmark for perf issues related to the nested property UI…like, if you can't make a few copies on stage, transform them a few times, delete, undo without crashing the app, probably cause for concern.

2018-08-29 18:50 UTC, stristr commented
(Slack link if you don't have it handy: https://the-haiku-team.slack.com/files/U7D14QLDB/FCDJ5JRQA/coin_icon.svg)

2018-08-29 20:16 UTC, stristr commented
@roperzh, this test flake is fixed in 92c844be56ce99e800afb178bd6503312bdbce3b. Feel free to cherry-pick in your branch if helpful.

2018-08-29 21:43 UTC, stristr commented
Re: ^ @roperzh, you can now just rebase (that commit is in `master`).

2018-09-25 16:03 UTC, roperzh commented
RECHECK!

2018-09-25 16:11 UTC, roperzh commented
This is ready to be reviewed 👀

2018-09-26 07:21 UTC, jonaias commented on packages/haiku-serialization/src/bll/Element.js
>        descendants.forEach((descendantElement) => {
Using for.. of might avoid creating arrow function that would be garbage collected? Probably doesn't matter much..

2018-09-26 07:24 UTC, jonaias commented on packages/haiku-timeline/src/components/ComponentHeadingRow.js
> +    const backgroundColor = depth > 1 || this.props.isExpanded ? 'transparent' : Palette.LIGHT_GRAY;
Add parenthesis to make faster to reason about operator precedence?

2018-09-26 07:27 UTC, jonaias commented on packages/haiku-timeline/src/components/ScrubberInterior.tsx
>      }
Switch instead cascaded if-else?

2018-09-26 07:48 UTC, jonaias commented
I took a look at the code and ran it here, including a project with infamous `Coin_Icon.svg`. I wasn't able to crash or see any bug/visual glitch.

I think a revision from someone else would be nice, otherwise LGTM.

2018-09-26 13:47 UTC, roperzh commented on packages/haiku-serialization/src/bll/Element.js
>        descendants.forEach((descendantElement) => {
This is not necessarily the case with v8! ⚙️ check [this out](https://v8.dev/blog/elements-kinds)

2018-09-26 13:47 UTC, roperzh commented on packages/haiku-timeline/src/components/ComponentHeadingRow.js
> +    const backgroundColor = depth > 1 || this.props.isExpanded ? 'transparent' : Palette.LIGHT_GRAY;
Good idea, thanks! 🤗

2018-09-26 13:49 UTC, roperzh commented on packages/haiku-timeline/src/components/ScrubberInterior.tsx
>      }
I agree with you, and I also always wanted to use a more readable approach, like for example:

```js
['timeline-scroll', 'time-display-mode-change'].includes(what)
```

But since this pattern is used in every other component in the timeline I vote to leave this as-is for consistency, what do you think?

2018-09-26 15:43 UTC, jonaias commented on packages/haiku-serialization/src/bll/Element.js
>        descendants.forEach((descendantElement) => {
Nice to know that performance wise is the same for both `for..of` and `forEach`.

2018-09-26 15:46 UTC, jonaias commented on packages/haiku-timeline/src/components/ScrubberInterior.tsx
>      }
I agree with leave as-is for consistency. :+1:

2018-09-29 02:08 UTC, stristr requested changes
Early result of manual QA noted here. (I am still reviewing code, but also just took it for a spin.)

 - [minor] The chevron next to subcomponents is in the wrong position when it's expanded [[screengrab](https://cl.ly/4dbe4237c223)]
 - [severe] Copied slices have a major UI issue. Open new project with default Sketch file, slice `haiku icon` from Sketch, and instantiate it. Works as expected. Copy and paste it, and the one you pasted gets [messed up](https://cl.ly/6921e8697d54); I also reproduced this opening an existing project that had the Haiku H instantiated which I created prior to checking out this branch. Things get [crazier](https://cl.ly/1c00667786b0) with `Coin_Icon.svg`. This issue seems to persist after you close and reopen a project. It does not occur if you instantiate the same slice twice, only if you copy and paste…

2018-10-10 15:58 UTC, roperzh commented
I think this is ready for another review

2018-10-12 17:36 UTC, stristr approved these changes

2018-10-12 19:50 UTC, stristr commented
@roperzh, your new fix seems to fix it for me! I'm going to merge this (LGTM), and try to get a build out for QA based on it. Nice work—and sorry if this is premature.

2018-10-12 19:50 UTC, merged