Preview mode
HaikuTeam/animator pull request #76
Opened 2017-11-07 23:38 UTC by roperzh

**What**

This adds logic to handle the preview mode, as described [here](https://haiku.quip.com/aWHpAEvMmR9N)

[Trello card](https://trello.com/c/79CV50wA/392-build-rudimentary-preview-mode)

**Comments**

- Besides the logic described in the Quip document we are also handling a bunch of edge cases and constraints like:
  - Copy/Cut/Paste are disabled on preview mode
  - Asset instantiation is disabled
  - Several keyboard shortcuts/interactions
- Some events interactions don't work properly (mouseover, keypress, etc) but they don't work properly in master too, they are being tackled by @roperzh in a separate PR as part of the events UI.
- I created a [namespace in `haiku-common`](https://github.com/HaikuTeam/mono/compare/preview-mode?expand=1#diff-fa3e0b219a520917f822eb2fd81942ec) to define interaction modes, the only place where they are still hardcoded is in the player, but I need to review with @matthewtoast if this is OK.

<img src="https://thumbs.gfycat.com/MiserlyInnocentBangeltiger-small.gif" alt="preview-mode-2.m4v GIF" width="100%">

2017-11-07 23:45 UTC, roperzh commented
Including @taylorpoe to review the UI/Design:

![screen shot 2017-11-07 at 20 43 15](https://user-images.githubusercontent.com/4419992/32523984-7bed0682-c3fc-11e7-82f5-b73f642d840c.png)

![screen shot 2017-11-07 at 20 43 08](https://user-images.githubusercontent.com/4419992/32523985-7c587200-c3fc-11e7-9125-4f249ae8c841.png)

![toggle](https://user-images.githubusercontent.com/4419992/32523973-6d9f1ed0-c3fc-11e7-9357-cc7f30f364d8.gif)

2017-11-09 00:39 UTC, taylorpoe requested changes
@roberzh as much as I love the toggle, I think the result is too text heavy. I think we should try something more minimal. I think this should work well:
![eyeball](https://d26dzxoao6i3hh.cloudfront.net/items/0V1M3141081E45221J1m/Image%202017-11-08%20at%204.35.46%20PM.png?v=599acb3c)

2017-11-09 00:41 UTC, taylorpoe commented
@roperzh eyeball svg icon is in the linearicons collection, which I believe you have.

2017-11-10 22:51 UTC, stristr commented on packages/haiku-common/config/experiments.json
> +    "development": true
Note: after #83 is merged this will simplify to `"development": true`.

2017-11-14 14:54 UTC, merged