Events ui
HaikuTeam/animator pull request #89
Opened 2017-11-16 17:43 UTC by roperzh

This is ready for review.

There will be probably a couple of bugs, but the most part is done and the functionality is finally here.

**Interesting bits**

- The events editor used to be a monolith file, this PR splits it into multiple components, which you can see in [components/EventHandlerEditor](https://github.com/HaikuTeam/mono/tree/events-ui/packages/haiku-glass/src/react/components/EventHandlerEditor)
- You may want to take a quick look at [HandlerManager](https://github.com/HaikuTeam/mono/pull/89/files#diff-9d3ac96cd39313832949398de3b47bf5)
- For the formatting issues: I ended up adding [yet another patch](https://github.com/HaikuTeam/mono/blob/events-ui/packages/haiku-glass/src/react/components/EventHandlerEditor/HandlerManager.js#L198), we should fix this, but I think it's going to take a significant amount of work/discussion and it belongs to another PR.
- There are two naive checks for the root element that will need special attention when implementing multicomponents, check https://github.com/HaikuTeam/mono/pull/89/commits/ffe298d5ed1c23a70f063d108d9163684a7d243a.

2017-12-04 14:34 UTC, tsortwehttam commented on packages/haiku-glass/src/react/Glass.js
> +  buildBoltInstance (x, y, rotationZ) {
Mentioning in case it hasn't come up yet: You may also need to account for negative scaling here. I.e. scale the element so that it is flipped over. For X, Y, and X+Y together.

2017-12-04 15:17 UTC, roperzh commented on packages/haiku-glass/src/react/Glass.js
> +  buildBoltInstance (x, y, rotationZ) {
Thank you! I'm looking into it now :)

2017-12-04 15:27 UTC, roperzh commented
Moving from wip -> ready for review 🎉

2017-12-04 15:39 UTC, roperzh commented
Updated main comment with some pointers/comments

2017-12-04 15:57 UTC, tsortwehttam commented on packages/haiku-glass/src/react/Glass.js
> +        this.setLastSelectedElement(this._component.findElementByComponentId(elementUID))
Note to self: Method call to change in multi-component.

2017-12-04 15:57 UTC, tsortwehttam commented on packages/haiku-glass/src/react/Glass.js
> +      )
Note to self: Method call to change in multi-component. (Move into modified ActiveComponent method which abstracts away the websocket hook.)

2017-12-04 15:59 UTC, tsortwehttam commented on packages/haiku-glass/src/react/Glass.js
> +              save={this.saveEventHandlers.bind(this)}
Nit: We should move method bindings to the constructor.

2017-12-04 16:00 UTC, tsortwehttam commented on packages/haiku-glass/src/react/Icons.js
> +}
Nit: We should eventually move this whole file into `haiku-ui` so we can easily share common icons.

2017-12-04 16:01 UTC, tsortwehttam commented on packages/haiku-glass/src/react/components/EventHandlerEditor/Editor.js
> +  }
Nit/future: After I merge multi-component, I'd like to move all logic like this into the BLL.

2017-12-04 16:03 UTC, tsortwehttam commented on packages/haiku-glass/src/react/components/EventHandlerEditor/HandlerManager.js
> +export default HandlerManager
Nit/future: Once I merge multi-component I'd like to move this entire file into the BLL.

2017-12-04 16:03 UTC, roperzh commented on packages/haiku-glass/src/react/Icons.js
> +}
+100, I know that we are probably going to do that post-launch, but I feel we are reaching to the point where is being painful to keep separate files for the Palette and the Icons.

2017-12-04 16:05 UTC, tsortwehttam commented on packages/haiku-glass/src/react/components/EventHandlerEditor/index.js
> +  shouldComponentUpdate ({element, visible, options}, nextState) {
Note to self: When merging multi-component I will need to check whether 'element' needs to be modified here.

2017-12-04 16:06 UTC, tsortwehttam commented on packages/haiku-plumbing/src/Master.js
> +
Note to self: Multi-component API change.

2017-12-04 16:07 UTC, tsortwehttam commented on packages/haiku-serialization/src/bll/ActiveComponent.js
>    /**
Note to self: All lines above need to be modified for multi-component.

2017-12-04 16:08 UTC, tsortwehttam commented on packages/haiku-serialization/src/bll/Element.js
> +
QUESTION: What is the purpose of those variables being assigned? Can this be removed?

2017-12-04 16:10 UTC, tsortwehttam commented on packages/haiku-timeline/src/components/FrameGrid.js
> +      }, 500)
QUESTION: What is the purpose of the timeout here?

2017-12-04 16:11 UTC, tsortwehttam commented on packages/haiku-timeline/src/components/Timeline.js
> +
Note to self: Fix for multi-component.

2017-12-04 16:11 UTC, roperzh commented on packages/haiku-serialization/src/bll/Element.js
> +
IIRC, the idea is to completely replace the pointer to `substructs[0].bytecode` with the new batch of `serializedEvents`. But, right now I'm not sure if makes sense

2017-12-04 16:20 UTC, roperzh commented on packages/haiku-timeline/src/components/FrameGrid.js
> +      }, 500)
My bad, I should have left a comment at lest!

The thing is, when a component listeners are updated, we trigger the `timeline-frame-action` event, but the event arrives here _before_ the component is updated in disk.

Since we are doing: `this.rootElement.getCustomEvents()` to get the listeners and display the little bolts in the timeline, we need to wait a "safe" amount of time till we can safely read all events from the component.

This is one of the things that I'm not happy about, if you have any ideas I will go for them, otherwise I will paste this as a comment.

2017-12-04 16:41 UTC, tsortwehttam commented on packages/haiku-serialization/src/bll/Element.js
> +
In this case, the variable `eventHandler` is just getting assigned to one value, and then to another value. So L214-215 aren't actually modifying anything (unless I'm missing something obvious). Is the intent to update something here?

2017-12-04 16:56 UTC, tsortwehttam commented on packages/haiku-timeline/src/components/FrameGrid.js
> +      }, 500)
Gotcha. This is fine to merge for now. But in the future we should try to avoid this kind of thing, since usually the result is "I solved one race condition by introducing two new race conditions" ;) (To be clear, I am guilty of this on many counts!)

Side note: We unfortunately have a significant amount of logic like this through the system. I've addressed a bit of it during multi-component, but we should think in general about how we can make logically explicit race conditions in the code, especially when those conditions are conceptually or organizationally far apart. 🏓

2017-12-04 16:58 UTC, tsortwehttam commented
Since there is a lot of code here, I'd like to also nominate @stristr to take a second look at this before giving the green light to merge (if he has time).

2017-12-04 23:45 UTC, stristr commented on packages/haiku-bytecode/src/actions/batchUpsertEventHandlers.js
> +  bytecode.eventHandlers[selectorName] = {}
Nit/syntactic sugar: L12-L16 can be rewritten as:

```
bytecode.eventHandlers = {
  ...bytecode.eventHandlers,
  [selectorName]: {},
}
```

2017-12-04 23:45 UTC, stristr commented on packages/haiku-bytecode/src/actions/batchUpsertEventHandlers.js
> +  bytecode.eventHandlers[selectorName] = {}
(b/c `{...undefined}` is `{}`)

2017-12-04 23:54 UTC, stristr commented on packages/haiku-serialization/src/utils/react2haiku.js
> +    children: children ? [react2haiku(reactInstance.props.children)] : []
qq: is `children` an array? I would expect this to be:

```
  children: reactInstance.props.children ? reactInstance.props.children.map(react2haiku) : []
```

2017-12-05 00:00 UTC, stristr commented on packages/haiku-glass/src/react/Glass.js
> +              save={this.saveEventHandlers.bind(this)}
Better: `save={() => { this.saveEventHandlers() }}`

2017-12-05 00:03 UTC, stristr commented on packages/haiku-glass/src/react/Icons.js
> +}
In case it wasn't already known (I figure it is since you LGTMed it), `haiku-ui-common` is already in master if you felt like moving it inside this PR.

2017-12-05 00:47 UTC, stristr commented
Overall LGTM! I left a few comments, mostly nits.

You may want to look carefully at the several opportunities to replace `this.foo = this.foo.bind(this)` in constructors which I noted…in some places it might not be the best call, but I think it usually fits the bill.

2017-12-05 00:53 UTC, tsortwehttam commented on packages/haiku-serialization/src/utils/react2haiku.js
> +    children: children ? [react2haiku(reactInstance.props.children)] : []
FWIW: I might be remembering this wrong, but -- during a deep foray into React last year, I recall noting that `children` can be any of these: a single React element, a single string, or an array of those. I believe this is because the JSX compiler may resolve `<a><b/></a>` to `React.createElement('a',React.createElement('b'))` instead of `React.createElement('a',[React.createElement('b')])`.

2017-12-05 00:59 UTC, stristr commented on packages/haiku-serialization/src/utils/react2haiku.js
> +    children: children ? [react2haiku(reactInstance.props.children)] : []
Interesting, I buy that (especially considering that Roberto's code appears to be working). We might want to at least note in a comment, in case there's a hidden bug we trigger sometime later, that we're not insulated against the cases where it's not a single React element.

2017-12-05 01:02 UTC, stristr commented
Style nit: I actually have a really hard time detecting the bottom boundary of the event selector menu ([screenshot](https://cl.ly/1y2e451P1p1s))—it really looks like there's a misplaced `  }` menu item down at the bottom.

2017-12-05 01:19 UTC, roperzh commented on packages/haiku-bytecode/src/actions/batchUpsertEventHandlers.js
> +  bytecode.eventHandlers[selectorName] = {}
I love it, thanks!

2017-12-05 01:40 UTC, stristr requested changes

2017-12-05 01:40 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/index.js
> +    this.onEditorRemoved = this.onEditorRemoved.bind(this)
I'm actually getting an error on this binding when I try it locally. TypeError: Invalid attempt to destructure non-iterable instance.

2017-12-05 01:40 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/Snippets.js
> +}
Something's up with the usability of the snippet menu ([screenshot](https://cl.ly/0m2l1n2X2m3L)). On my laptop screen, it gets cut off and I can't scroll beyond one or two items. When I do scroll, it flickers and pushes down the menu.

2017-12-05 01:40 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/ElementTitle.js
> +  container: {
For some reason I get CSS cursor: grab on this container. Not sure where it's coming from, but it's super weird and makes me think I should be able to drag/resize the action editor. (It's okay that I can't, but would be much nicer if I can.)

2017-12-05 01:40 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/Snippets.js
> +}
Additionally, if I have N > 1 event listeners, I can only use the snippet menu at all on the first one. All subsequent ones are just a noop when I click the button.

2017-12-05 01:40 UTC, stristr commented on packages/haiku-glass/src/react/Menu.js
> +    position: 'absolute',
Something about the absolute positioning is wrong for N > 1 events. Specifically, I see the menu here on the second of two events: https://cl.ly/193m2M1M292a.

If there are three or more, subsequent menus are absolutely positioned off-screen on Glass!

2017-12-05 01:40 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/ElementTitle.js
> +            <span style={STYLES.buttonText}>New Action</span>
Nit 1: It's kind of weird that this button doesn't change at all when I hover/click on it.

Nit 2: the "new action" behavior works great for cycling through the available listener types and making sure we don't make e.g. duplicate "click" listeners. But after I have added all available actions, the button remains but does nothing. It feels like it should ideally disappear or get visibly disabled.

2017-12-05 01:40 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/Snippets.js
> +    } else {
It feels like maybe logic is missing for cases where there is selected text. My expectation as a user is that if text is selected and I add a snippet, the snippet should replace the text.

2017-12-05 01:40 UTC, stristr commented on packages/haiku-timeline/src/components/EventHandlerTriggerer.js
> +        <Bolt color={this.getBoltColor()} />
Inexplicably, if I resize an element while the Bolt is present, the bolt disappears. If I deselect and then re-select, it appears. No issue with translation.

2017-12-05 01:40 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/Snippets.js
> +    shell.openExternal('https://docs.haiku.ai/using-haiku/summonables.html')
Any way we can shim in a separator and somehow style the docs separately? It feels weird to have "docs" as the "last snippet"—I was confused why it took me to a browser and didn't just add a snippet.

2017-12-05 01:40 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/Snippets.js
> +}
Final note: the first issue reported (can't see full snippet menu) only occurs with N > 1 event listeners. Everything seems fine when there's exactly one event listener.

2017-12-05 01:42 UTC, stristr commented on packages/haiku-timeline/src/components/icons/Bolt.js
> +export default ({color = '#93999A'}) => (
Nit: we can use svgo to remove the redundant nested `<g>` elements and simplify the `transform='translate(...)'` calls by applying them to the path.

2017-12-05 01:43 UTC, stristr commented on packages/haiku-timeline/src/components/Timeline.js
> +            paddingTop: '5px',
Nit: probably should prefer `5` to `'5px'` for consistency with the rest of this file.

2017-12-05 01:46 UTC, stristr commented on packages/haiku-glass/src/react/Menu.js
> +    this.toggleOpen = this.toggleOpen.bind(this)
Here and throughout: except in rare cases where we are actually creating a perf bottleneck in a component that re-renders frequently, it should save local load to use fat arrows instead of instance-bound functions. e.g. instead of doing `this.a = this.a.bind(a); ... onClick={this.a}`, just do `onClick={() => this.a()}`.

2017-12-05 01:48 UTC, stristr commented on packages/haiku-serialization/src/bll/ActiveComponent.js
> +    console.log(metadata, cb)
Probably should remove this before submit.

2017-12-05 01:53 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/EventSelector.js
> +          {this.renderMenuItems()}
Nit: `renderMenuTrigger` and `renderMenuItems` are good candidates for a ES6 [getters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get).

If you haven't used, you would basically change:

```
a() {
  return x
}

render() {
  return <Thing a={this.a()} />
}
```

with

```
get a() {
  return x
}

render() {
  return <Thing a={this.a} />
}
```

2017-12-05 01:57 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/HandlerManager.js
> +      })
Fussy nit (please don't change, but note for future): there isn't a huge advantage to using Map over a plain Object when the keys are all known to be strings.

2017-12-05 01:58 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/index.js
> +
Nit: prefer

```
if ((a) || (b)) {
  return x
}
```

if `(a)` and `(b)` are conditions that both return `x`.

2017-12-05 01:59 UTC, stristr commented on packages/haiku-serialization/src/bll/Element.js
> +
👍, likewise confused.

2017-12-05 02:00 UTC, stristr commented on packages/haiku-timeline/src/components/EventHandlerTriggerer.js
> +    return this.props.element.getDOMEvents().length ? '#4DCEDA' : '#738C8F'
Nit: should put these in `Palette`. (Also see in `<FrameAction />`.)

2017-12-05 02:02 UTC, stristr commented on packages/haiku-timeline/src/components/Timeline.js
> +      () => {}
Wish list, not for now: export `() => {}` as noop in `haiku-common`, and use it instead of `() => {}`.

2017-12-05 02:09 UTC, tsortwehttam commented on packages/haiku-timeline/src/components/Timeline.js
> +      () => {}
FWIW, some of this will be tucked away with multi-component.

2017-12-05 03:43 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/HandlerManager.js
> +    for (let [event, rawHandler] of Object.entries(appliedEventHandlers)) {
Nit: for `(const ...)`.

2017-12-05 03:43 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/HandlerManager.js
> +    for (let event of this.applicableEventHandlersList) {
Nit: for `(const ...)`.

2017-12-05 03:43 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/HandlerManager.js
> +        result.push(value)
Nit: for `(const ...)` in both loops.

2017-12-05 13:23 UTC, roperzh commented on packages/haiku-glass/src/react/Icons.js
> +}
I was in doubt about moving it inside this PR because there's already too much to take and we need to figure out a plan, we have a `Icons.js` file in every webview (glass, creator, timeline) and the icons have sightly different markup between files, so I believe that it will require some extra care.

If you feel like it will be a good idea to do it in this PR, I'm in! or maybe at we can move this file and figure out later what to do with the rest?

2017-12-05 13:58 UTC, roperzh commented on packages/haiku-glass/src/react/components/EventHandlerEditor/Snippets.js
> +    shell.openExternal('https://docs.haiku.ai/using-haiku/summonables.html')
cc @taylorpoe

2017-12-05 14:08 UTC, roperzh commented on packages/haiku-glass/src/react/components/EventHandlerEditor/HandlerManager.js
> +      })
For this particular case, i choose a `Map` because it preserves the order in which the elements are `set`.

We need to preserve order because when the user presses the `New Action` button I would expect the item to be added at the top (or bottom) of the list.

I considered using an array, but it was too much of a hassle.

Just interested: do you think that any other data structure could have fill the purpose?

2017-12-05 14:38 UTC, roperzh commented on packages/haiku-glass/src/react/Menu.js
> +    position: 'absolute',
Fixed! thanks for pointing that out.

2017-12-05 14:51 UTC, roperzh commented on packages/haiku-glass/src/react/components/EventHandlerEditor/Snippets.js
> +}
This should be fixed, thanks for the heads up!

2017-12-05 14:57 UTC, roperzh commented on packages/haiku-glass/src/react/components/EventHandlerEditor/ElementTitle.js
> +  container: {
Fixed!

2017-12-05 14:58 UTC, roperzh commented on packages/haiku-glass/src/react/components/EventHandlerEditor/ElementTitle.js
> +            <span style={STYLES.buttonText}>New Action</span>
Nit 1: agreed 100%, will add a comment for when we unify styles, otherwise I will have to copy and paste default button styles.

Nit 2: fixed!

2017-12-05 14:59 UTC, roperzh commented on packages/haiku-glass/src/react/components/EventHandlerEditor/index.js
> +    this.onEditorRemoved = this.onEditorRemoved.bind(this)
Fixed!

2017-12-05 15:22 UTC, roperzh commented on packages/haiku-timeline/src/components/icons/Bolt.js
> +export default ({color = '#93999A'}) => (
Done!

2017-12-05 15:30 UTC, roperzh commented on packages/haiku-bytecode/src/actions/batchUpsertEventHandlers.js
> +  bytecode.eventHandlers[selectorName] = {}
note: the compiler is complaining about this one, but it's valid syntax. Probably a bug, maybe we should upgrade a package?

2017-12-05 16:30 UTC, taylorpoe commented on packages/haiku-glass/src/react/components/EventHandlerEditor/Snippets.js
> +    shell.openExternal('https://docs.haiku.ai/using-haiku/summonables.html')
Yeah good thought. We should use an icon here to help the user understand they're about to blast over to the web. https://cl.ly/3t273z3a2i2a. @roperzh I have this icon in `haiku-creator` in the new Dashboard UI's `icons.js`. Feel free to add a task for me to circle back in add it here to the Actions UI after our PRs, or just copy the svg here: https://github.com/HaikuTeam/mono/pull/102/files#diff-8722beaa347e20a924afe7b4fd9e5b55R71 Whatever you think makes the most sense.

2017-12-05 17:10 UTC, roperzh commented on packages/haiku-glass/src/react/components/EventHandlerEditor/Snippets.js
> +    shell.openExternal('https://docs.haiku.ai/using-haiku/summonables.html')
@taylorpoe I will need that icon on the publish UI too (was using the one from the icon set which is a bit different). I will create a task in asana for either one of us to pick.

2017-12-05 18:03 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/HandlerManager.js
> +      })
This makes perfect sense. Thanks for explanation!

Only possibly "better" (read: maybe more efficient) data structure is an array of objects. But I would never choose it here due to tradeoff between ergonomics and efficiency.

2017-12-05 18:04 UTC, stristr commented on packages/haiku-glass/src/react/Icons.js
> +}
Let's hold off!

2017-12-05 18:05 UTC, stristr commented on packages/haiku-bytecode/src/actions/batchUpsertEventHandlers.js
> +  bytecode.eventHandlers[selectorName] = {}
Oh yeah, bytecode is one of the packages that doesn't compile. I'd just leave it, with a comment to fix when we standardize to TypeScript if you're feeling ambitious!

2017-12-05 18:09 UTC, stristr commented on packages/haiku-glass/src/react/components/EventHandlerEditor/index.js
> +
@roperzh, sorry, I don't think this is correct anymore.

I meant:

```
if ((options && options.frame !== this.props.options.frame) || visible !== this.props.visible) {
  return true
}
```

2017-12-06 00:36 UTC, roperzh commented on packages/haiku-glass/src/react/components/EventHandlerEditor/index.js
> +
Yes, there is only one explanation for this: I am dumb 😅 

Sorry for the mental hiccup.

2017-12-06 08:37 UTC, stristr approved these changes

2017-12-06 08:39 UTC, stristr commented
Hey @roperzh, before you merge and because I think the comment seems to be missing in certain views, wanted to make sure you were at least aware of the report [here](https://github.com/HaikuTeam/mono/pull/89#discussion_r154824965) and okay with it. Basically, when I resize an element below a certain width/height, the bolt icon disappears and I'm left with just a circle and no bolt. It remains gone even if I size back to the original, unless I deselect and then reselect the element.

2017-12-06 13:11 UTC, roperzh commented
Thanks! I'm aware of that comment (thanks for pointing that out!) but I haven't found a solution yet. It is very probably related to the player, as we had a similar issue with the bolt and that was the cause. I will keep you posted

2017-12-06 13:30 UTC, merged